spring:
  datasource:
    url: jdbc:mysql://nanchoidb.cnzxc5x3qe0b.ap-northeast-2.rds.amazonaws.com:3306/mealPrep
    username: admin
    password: Choi100~
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
    open-in-view: false
app:
  firebase-bucket: mealprep-b96e0.appspot.com

server:
  port: 443
  ssl:
    enabled: true
    key-store-password: Choi100~
    key-store-type: PKCS12
    key-store: /home/ubuntu/FriendKeystore.p12
